# This uses newer and faster docker based build system
sudo: false
language: php
services: mysql
notifications:
  on_success: always
  on_failure: change
  slack:
    rooms:
      - wilokegroup:1bS7SWI4jj1Jy9Krr3RSHIwd#general
      - wilokegroup:1bS7SWI4jj1Jy9Krr3RSHIwd#random
php:
  - 7.2
install:
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
env:
    - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test
before_script:
  # Install composer packages before trying to activate themes or plugins
  # - composer install
  - git clone https://github.com/wilokecom/wordpress-test-travis.git wordpress-test-travis
  - bash wordpress-test-travis/bin/install-wp-tests.sh wp_test root '' 127.0.0.1 latest
  - gem install redmine-installer
  - composer update
  - composer dump-autoload
script: phpunit --configuration phpunit.xml --coverage-text
